In [1]:
pip install pandas

                                              0.0/11.6 MB ? eta -:--:--
                                              0.2/11.6 MB 5.9 MB/s eta 0:00:02
     -                                        0.5/11.6 MB 6.2 MB/s eta 0:00:02
     --                                       0.7/11.6 MB 5.4 MB/s eta 0:00:03
     --                                       0.7/11.6 MB 4.3 MB/s eta 0:00:03
     --                                       0.8/11.6 MB 3.6 MB/s eta 0:00:04
     --                                       0.8/11.6 MB 3.2 MB/s eta 0:00:04
     ---                                      0.9/11.6 MB 2.9 MB/s eta 0:00:04
     ---                                      1.0/11.6 MB 2.8 MB/s eta 0:00:04
     ---                                      1.1/11.6 MB 2.7 MB/s eta 0:00:04
     ---                                      1.2/11.6 MB 2.5 MB/s eta 0:00:05
     ----                                     1.2/11.6 MB 2.5 MB/s eta 0:00:05
     -----                                    1.5/11.6 MB 2


[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [14]:
import pandas as pd
import numpy as np

1

In [6]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array

<IntegerArray>
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Length: 10, dtype: Int64

4

In [18]:
array_maiores_que_5 = array[array>5]
print('valores maiores que 5:', array_maiores_que_5)

valores maiores que 5: <IntegerArray>
[6, 7, 8, 9, 10]
Length: 5, dtype: Int64


3

In [20]:
array1to5= np.array([1, 2, 3, 4, 5])
array6to10 = np.array([6, 7, 8, 9, 10])
soma_arrays = array1to5 + array6to10
print({'a soma dos arrays é : ', soma_arrays})

TypeError: unhashable type: 'numpy.ndarray'

2


In [ ]:
quarto_elemento = array1to10[3]
print('o quarto elemento do array é: ', quarto_elemento)

5

In [22]:
print('media:', array.mean())
print('desvio padrão:', array.std())

media: 5.5
desvio padrão: 3.0276503540974917


6

In [23]:
array_concat = np.concatenate([array1to5, array6to10])
print('concatenação:')
print(array_concat)

concatenação:
[ 1  2  3  4  5  6  7  8  9 10]


7

In [24]:
array1 = np.arange(1, 11)
array2 = np.arange(10, 0, -1)

resultado = array1 - array2

print('resultado da subtração: ', resultado )

resultado da subtração:  [-9 -7 -5 -3 -1  1  3  5  7  9]


8

In [26]:
array1 = np.arange(1, 11)
array_ordenado = np.sort(array1)[::-1]
print(array_ordenado)

[10  9  8  7  6  5  4  3  2  1]


9

In [27]:
arr = np.array([0, 4, 2, 6, 5, 9, 6])
print('valores duplicados:', np.unique(arr).size !=arr.size)

valores duplicados: True


10


In [28]:
print ('Silicing do terceiro ao setimo alemnto:')
print(arr[2:7])

Silicing do terceiro ao setimo alemnto:
[2 6 5 9 6]


In [16]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
tupla = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
df_series = pd.Series(tupla)


In [17]:
df_series

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [10]:
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [11]:
tupla

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)